# NOTE: Generated By HttpRunner v3.1.6
# FROM: get_token.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseGetToken(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/cgi-bin/token")
            .get("https://api.weixin.qq.com/cgi-bin/token")
            .with_params(
                **{
                    "appid": "wx74a8627810cfa308",
                    "grant_type": "client_credential",
                    "secret": "e40a02f9d79a8097df497e6aaf93ab80",
                }
            )
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Cache-Control": "no-cache",
                    "Connection": "keep-alive",
                    "Host": "api.weixin.qq.com",
                    "Postman-Token": "50f8bb1a-7826-49f8-835e-ec889063b7cc",
                    "User-Agent": "PostmanRuntime/7.28.0",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; encoding=utf-8")
            .assert_equal(
                "body.access_token",
                "45_zo0cI1hRQhNoUKfLxsDAyCw0ozZZB_lc7Gy62bj1H9uRnLlXshYqH_g5FBuWC3VlmNk8enL-hCsbN3qumyyg1mRTjRtuiriApZd6ZKeDxu0oikKn4yF4PgUautvgfciX5O07iIxsWJj7CCVTPQCfAEAZAM",
            )
            .assert_equal("body.expires_in", 7200)
        ),
    ]


if __name__ == "__main__":
    TestCaseGetToken().test_start()
