# NOTE: Generated By HttpRunner v3.1.6
# FROM: select_flag.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseSelectFlag(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/cgi-bin/token")
            .get("https://api.weixin.qq.com/cgi-bin/token")
            .with_params(
                **{
                    "grant_type": "client_credential",
                    "appid": "wx74a8627810cfa308",
                    "secret": "e40a02f9d79a8097df497e6aaf93ab80",
                }
            )
            .with_headers(
                **{
                    "User-Agent": "PostmanRuntime/7.28.0",
                    "Accept": "*/*",
                    "Cache-Control": "no-cache",
                    "Postman-Token": "92e98971-c9e4-481b-adee-a58166bf3f49",
                    "Host": "api.weixin.qq.com",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Connection": "keep-alive",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; encoding=utf-8")
            .assert_equal(
                "body.access_token",
                "45_MQlGc0jjs7EIcwjUBBkd5jYmrDC98ogaLocm5coHgn1jaCxQaLLwxMFoSS7bL0MsLuxxQhyV2A0D9pFG66vwVAm2VvjcdcvbpbKqaPKBIns6LThBt9pWeVlKeN38tR3HN9IS84JOkCXfGjMRSBOhAJAYHU",
            )
            .assert_equal("body.expires_in", 7200)
        ),
        Step(
            RunRequest("/cgi-bin/tags/get")
            .get("https://api.weixin.qq.com/cgi-bin/tags/get")
            .with_params(
                **{
                    "access_token": "45_MQlGc0jjs7EIcwjUBBkd5jYmrDC98ogaLocm5coHgn1jaCxQaLLwxMFoSS7bL0MsLuxxQhyV2A0D9pFG66vwVAm2VvjcdcvbpbKqaPKBIns6LThBt9pWeVlKeN38tR3HN9IS84JOkCXfGjMRSBOhAJAYHU"
                }
            )
            .with_headers(
                **{
                    "User-Agent": "PostmanRuntime/7.28.0",
                    "Accept": "*/*",
                    "Cache-Control": "no-cache",
                    "Postman-Token": "332d513f-e463-4a6f-8752-758b06f00009",
                    "Host": "api.weixin.qq.com",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Connection": "keep-alive",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; encoding=utf-8")
        ),
    ]


if __name__ == "__main__":
    TestCaseSelectFlag().test_start()
