# NOTE: Generated By HttpRunner v3.1.6
# FROM: Untitled.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseUntitled(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/FundMCApi/FundMBNew/FZH15DynamicPostList2")
            .post(
                "https://jijinbaapi.eastmoney.com/FundMCApi/FundMBNew/FZH15DynamicPostList2"
            )
            .with_headers(
                **{
                    "Host": "jijinbaapi.eastmoney.com",
                    "Content-Type": "application/x-www-form-urlencoded",
                    "Content-Length": "298",
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Connection": "keep-alive",
                    "GTOKEN": "C59338F8EE684BB2A6E01353457F31be",
                    "User-Agent": "EMProjJijin/6.4.8 (iPhone; iOS 14.6; Scale/2.00)",
                    "Accept-Language": "zh-Hans-CN;q=1",
                    "Referer": "https://mpservice.com/a461099f332046f0b32783c5d3d980a8/release/pages/index/index",
                    "clientInfo": "ttjj-iPhone11,8-iOS-iOS14.6",
                }
            )
            .with_data(
                {
                    "ApiType": "4",
                    "CToken": "",
                    "CustomerNo": "",
                    "MobileKey": "ACE87AB5-50F8-48B7-A2AF-51B043BEB8D7",
                    "Passportid": "",
                    "PhoneType": "IOS14.6.0",
                    "ServerVersion": "6.4.8",
                    "TimePoint": "0",
                    "UToken": "",
                    "UserId": "",
                    "ZHCode": "10198717",
                    "appVersion": "6.4.8",
                    "customerNo": "",
                    "deviceid": "ACE87AB5-50F8-48B7-A2AF-51B043BEB8D7",
                    "pageSize": "1",
                    "plat": "Iphone",
                    "product": "EFund",
                    "version": "6.4.8",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=utf-8")
            .assert_equal("body.ErrorCode", 0)
            .assert_equal("body.FirstError", None)
            .assert_equal("body.Success", True)
            .assert_equal("body.HasWrongToken", False)
            .assert_equal("body.TotalCount", 0)
            .assert_equal("body.Expansion", None)
        ),
    ]


if __name__ == "__main__":
    TestCaseUntitled().test_start()
